# Generated by Django 4.2.20 on 2025-03-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('brand', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
    ]
